name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests
      run: |
        cd src-tauri
        cargo test --all --verbose

    - name: Run Lints
      run: |
        cd src-tauri
        cargo fmt --check
        cargo clippy -- -D warnings  
