name: Rust CI

# Run test and try build 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version 
      
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings  

      - name: Test 
        run: |
          cargo test --all

      - name: Build
        run: |
          cargo build --release