name: Rust

on:
  push:
    branches: [ "main" ]
    paths: 
      - "src-tauri/**"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "src-tauri/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update -y 
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Run tests
      run: |
        cd src-tauri
        cargo test --all --verbose

    - name: Run Lints
      run: |
        cd src-tauri
        cargo fmt --check
        cargo clippy -- -D warnings  
